### ISSUE TITLE
[Feature request]: publish the values of the analog input

### ISSUE THREAD

**Issue by RonaldHiemstra** [sblantipodi/glow_worm_luciferin#29]
### Describe the solution you'd like

I love your project, I also use it on dark and rainy working days as a background lighting.
I would like to extend the ESP with an LDR sensor to measure the environment and use this to control the brightness of the LEDs.

**Comment by sblantipodi** [comment]
Hi @RonaldHiemstra,
thank you for your interest in Luciferin and for the kind words.

This is a good idea, I'll leave this feature request open until  I'll have time to implement it.
If someone wants to implement it it's obviously fine.

In the mean time, if you have an MQTT environment like Home Assistant, you can create an automation that sends the brightness information to Glow Worm via MQTT or via an HTTP GET.

If you are interested in the MQTT way I can send you the topic and the payload needed to set the brightness.

**Comment by RonaldHiemstra** [comment]
> If you are interested in the MQTT way I can send you the topic and the payload needed to set the brightness.

I currently have a dedicated ESP32 with an LDR, which publishes its ADC value (averaged over a few seconds) to MQTT (only if the difference is larger than a certain limit, because I don't want continuous changing backlight).
I control the brightness of the Glow Worm is with Home Assistant.
It works very nice this way 😃 (after finding a good location for the LDR, with minimum influence by Glow Worm, otherwise it starts blinking 🤣).

**Comment by sblantipodi** [comment]
very nice, thank you for sharing :)

**Comment by sblantipodi** [comment]
Hi @RonaldHiemstra, I'm going to implement this feature in the next releases.
Can I ask you where did you put the LDR?

My ESP is behind the monitor, if the LDR is near to the ESP behind the monitor the LED strip may influence the measurement from the LDR.

Any tips for a good placement for the LDR?
