### ISSUE TITLE
[Feature request]: SK6812 support

### ISSUE THREAD

**Issue by kopidoo** [sblantipodi/glow_worm_luciferin#31]
### Is your feature request related to a problem? Please describe

A new SK6812 LED pixel protocol implementation would be great to have.
These LEDs can have a dedicated white channel with warm, neutral or cold colour temperature. Thanks to this the colour representation is much better that the normal RGB LEDs, especially the greyscale and the lower brightness hues.

### Describe the solution you'd like

Support of the SK6812 with the following features:
Switch between the white management modes:
- RGB: white is reproducedonly by RGB components (not so precise colour representation, white channel is not used)
- RGBW: white is reproduced only with the white component (lower power consumption)
- RGBW mixed: all four channels are used for white (high power consumption, maxed out brightness)

### Describe alternatives you've considered

I have no idea of other alternatives.

**Comment by sblantipodi** [comment]
This is one of the high priority feature for the next releases.
I will give an ETA when it's possible.
