### ISSUE TITLE
How to reset settings?

### ISSUE THREAD

**Issue by whakru** [sblantipodi/glow_worm_luciferin#37]
### Firmware type

FULL

### What is the stream method?

WiFi Stream

How to reset settings? I made a wrong mqtt setup and esp freezes and won't connect.
Does he have a backup wifi hotspot for his wrong dial?

**Comment by sblantipodi** [comment]
Hi @whakru please reflash the firmware from web installer and reconfigure WiFi/mqtt settings.

https://sblantipodi.github.io/glow_worm_luciferin/

**Comment by whakru** [comment]
is it possible to somehow ignore the lack of connection to mqtt?  I am using Mqtt just for remote management via HA.  It's not a core protocol and I would like to continue using fireflies over Wi-Fi without being able to connect to Mqtt.  You can also display the mqtt connection status on the web and in the application.

**Comment by sblantipodi** [comment]
Hi @whakru, this is an interesting feature that can be added in the next releases.
I don't have an ETA yet but I'll implement it for sure.

**Comment by whakru** [comment]
I'm sorry, I don't understand what is "ETA"?

**Comment by sblantipodi** [comment]
@whakru sorry for the late reply, I have seen your answer now.
ETA = Estimated Time of Arrival 

this fix will be implemented in future releases. in the mean time please reflash the firmware from the web installer as suggested in the previous reply.

thanks!
