### ISSUE TITLE
[Feature request]: Support for Dotstar LED strips

### ISSUE THREAD

**Issue by CptnNoFuture** [sblantipodi/glow_worm_luciferin#42]
### Is your feature request related to a problem? Please describe

First off: Great work with this software. It's the best custom Ambilight solution I've found so far.
Sadly only Neopixel strips are supported at the moment. I would like to use a Dotstar LED strip (like APA102, SK9822).

### Describe the solution you'd like

The Neopixelbus library also supports Dotstar LEDs via DotStarSpiMethod and corresponding features. Would it be possible to integrate these into the firmware as an option?

### Describe alternatives you've considered

I've tinkered crudely with the code of GlowWorm v5.7.2 myself and got it working on an ESP8266 (sadly not on an ESP32) for a SK9823. But "official/native"support for this feature would make things a little bit easier and increase the range of possible setups, especially as the Dotstars are a little bit more responsive fps-wise in my experience.

**Comment by sblantipodi** [comment]
Hi, thanks for the kind words. It is a feature that will be implemented for sure. I don't know when but it will be implemented. :)

**Comment by Ilithia** [comment]
Hi. If you're going to add support for these leds, could you also make possible to control global brightness of them? It's the feature that allow to control brightness independent of color range. Would also be very useful to have independent global brightness control of certain leds like top, bot, and sides, or just by the numbers.

**Comment by sblantipodi** [comment]
@Ilithia when the support will be added, it will be done with this in mind, thanks.

**Comment by sblantipodi** [comment]
@Ilithia I'm adding the support for DotStar LEDs for the next release.

With the current version of Luciferin you can control the brightness and it doesn't affect the colour that much,
there is a slider for the brightness.

Can you tell me what is the purpose of having per LED brightness control?
