### ISSUE TITLE
[Bug]: no connection to mqtt

### ISSUE THREAD

**Issue by whakru** [sblantipodi/glow_worm_luciferin#43]
### Firefly Luciferin version

last

### Glow Worm Luciferin version

last

### Firmware type

FULL

### What is the stream method?

WiFi Stream

### How to reproduce

for some reason, there is no connection via mqtt after entering all the data, the device no longer wakes up...
Logs: 
```
MQTT attempts= 
6 
Connecting to 
MQTT Broker... 
MQTT Last Will Params: 
willTopic: 0 
willPayload: 0 
qos: 1 
retain: 0 
clean session: 1 
MQTT attempts= 
7 
Connecting to 
MQTT Broker... 
MQTT Last Will Params: 
willTopic: 0 
willPayload: 0 
qos: 1 
retain: 0 
clean session: 1
```

I would also like to see this menu not only after the firmware, but also before it.  along with viewing logs.
![Ci38-CqmSpw](https://user-images.githubusercontent.com/22603145/193392152-60f819e3-ff81-459a-bcd8-c53d073ea757.jpg)

**Comment by sblantipodi** [comment]
Ho @whakru as far as I know you are using luciferin for some time now.
Is this mqtt problem recent? Is there something changed on your mqtt server?
Have you ever used mqtt previously with Luciferin?

Can you elaborate more the problem please?

**Comment by whakru** [comment]
> Ho @whakru as far as I know you are using luciferin for some time now. Is this mqtt problem recent? Is there something changed on your mqtt server? Have you ever used mqtt previously with Luciferin?
> 
> Can you elaborate more the problem please?

I have not used mqtt before.  I wanted to use it to control modes with Home Assistant.  but so far I haven't been able to.

**Comment by whakru** [comment]
I am using mqtt mosquito broker in HA.  maybe I'm not entering the address correctly, namely the protocol.  Could you suggest a template?  my server is on LAN at 192.168.31.31:1883 (1884 web socket)

**Comment by whakru** [comment]
![Screenshot_2022-10-01-14-56-17-733_io homeassistant companion android](https://user-images.githubusercontent.com/22603145/193408676-a12ad084-3199-4814-861d-b3556a71868b.jpg)

**Comment by sblantipodi** [comment]
sorry for the late reply @whakru 
please post your `FireflyLuciferin.yaml` file, you'll find it in your `~/Documents/FireflyLuciferin` folder.

please post a screenshot of the webinterface in the mqtt settings page, please access the web interface of your ESP by visiting its IP, then click the "three lines" button on the top right corner... I mean this screen.

<img width="526" alt="image" src="https://user-images.githubusercontent.com/4722227/194403367-dc0a6706-1ca2-4b79-b6e1-79406bf57543.png">

this will help me helping you :)
