### ISSUE TITLE
[Feature request]: Support for the 'Ethernet Add-on Board' version of the QuinLED-Dig-Uno 

### ISSUE THREAD

**Issue by speakn2pabst** [sblantipodi/glow_worm_luciferin#44]
### Is your feature request related to a problem? Please describe

The current provided firmwares include support for data communication across WiFi and/or USB cable, but not the Ethernet cable alternative.   

### Describe the solution you'd like

A firmware including Ethernet capability for this device version. :)

### Describe alternatives you've considered

Using the Ethernet instead of WiFi may be preferable for some users to reduce WiFi congestion or possibly for less energy consumption, although that second point is speculation.  Also the device supports it, so why not?  :p 

Thanks for your consideration!

**Comment by sblantipodi** [comment]
Hi @speakn2pabst,
thanks for your interest in Luciferin and for sharing your ideas.

I have added the label keep, I will add this feature when possible.

**Comment by sblantipodi** [comment]
there are various users asking for this support, at the moment I don't have an ethernet board, 
if someone wants to send me it I'll add the support when possible.
