### ISSUE TITLE
[Bug]: Setup Web Interface requires internet connection

### ISSUE THREAD

**Issue by jkowalk** [sblantipodi/glow_worm_luciferin#52]
### Firefly Luciferin version

-

### Glow Worm Luciferin version

5.10.6

### Firmware type

FULL

### What is the stream method?

WiFi Stream

### How to reproduce

I just noticed, that with the newest firmware version the setup page, that you can access over the hotspot if not configuration was found, relies on files on the public internet. Unless your device has an internet connection and is connected to the hotspot of the esp at the same time, the interface is not usable because the files cannot be downloaded.

In version 5.9.7 this is not an issue.

Here are some pictures how the web interface on 5.10.6 looks like if only connected to the device hotspot:
Web Interface        |  Unreachable files
:-------------------------:|:-------------------------:
![image](https://github.com/sblantipodi/glow_worm_luciferin/assets/58106486/97b5d638-45bd-4ee0-9811-6602be9c47a5)  | ![image](https://github.com/sblantipodi/glow_worm_luciferin/assets/58106486/5ae79627-b9c7-4971-8e07-f94abcd59925)

Thanks a lot for your work!

**Comment by sblantipodi** [comment]
Hi @jkowalk 
thanks for pointing this out...

This is not really a bug but a design choice to reduce the firmware footprint.

is there some real world scenarios where devices are not connected to the internet this days?

**Comment by jkowalk** [comment]
OK, I see your point. It depends on the way the operating system handles the different networks. On Windows with Ethernet connected to the Internet and Wi-Fi connected to the Esp, all resources were loaded. But on my smartphone (Android 12) it only used the Wi-Fi and ignored the cellular connection. So the page was unusable there.

I guess the setup page doesn't need to be anything fancy, just a simple form will do the job. Maybe it's possible to include the JavaScript so that it is still possible to submit the settings.

**Comment by sblantipodi** [comment]
@jkowalk great point. adding the keep label and fixing it in the future... :)
