### ISSUE TITLE
Typo in web flasher

### ISSUE THREAD

**Issue by TomasHubelbauer** [sblantipodi/glow_worm_luciferin#54]
### Describe the solution you'd like

There is a typo in the web flasher:
https://sblantipodi.github.io/glow_worm_luciferin/

<img width="595" alt="image" src="https://github.com/sblantipodi/glow_worm_luciferin/assets/6831144/1c613b43-9640-41a6-b747-b4191d5180f4">

In the second paragraph, S2 is missing and S3 is repeated twice. I looked at the source and found `docs/esp_web_tools` but it seem to be manually uploaded minified files so I did not send a PR.

**Comment by sblantipodi** [comment]
@TomasHubelbauer fixed thanks!
