### ISSUE TITLE
Purpose and Need for the Home Assistant Automations?

### ISSUE THREAD

**Issue by Teleportist** [sblantipodi/glow_worm_luciferin#7]
I've noticed that the Luciferin integration has added a few automations to my Home Assistant.

Of these 'gw_time_publisher' seems to be running every 10 seconds and 'PC Animation Speed' has never run.

I have the other 5 Glowworm/LGlowworm automations disabled.

Would you kindly tell me the purpose of these automations and if they are required please?
As I can still control the lights from HA and the Firefly program still seems to be communicating
with my HT PC, via MQTT.*

* Although I have noticed it's dropping frames and stuttering. Particularly when watching 720p videos
through Kodi. I don't think SD is so bad. Will open a separate issue for that though.

**Comment by sblantipodi** [comment]
Hi @Teleportist I will try to explain the purpose of the automations.
they are optional but useful if you want to control Luciferin via HA.

HA integration have one "input_boolean".

```
input_boolean:
  solideffect
```
it is used as a toggle to turn ON/OFF the ambient light effect from HA.

These automations:
`alias: GlowWorm Solid Effect OFF` and  `alias: GlowWorm Solid Effect ON`
listen for that input_boolean and sends a message to Firefly Luciferin to START/STOP the ambient light effect.

this automation
`alias: PC Animation Speed`
is used to increase/decrease the speed of the light effect that you can select from the HA light entity.

`gw_time_publisher` is just a status automation.
some MQTT servers disconnects peripherals that doesn't communicate frequently.
it's just a ping pong automation to keep the connection alive.
most MQTT devices works that way.

Other automations are triggered from the Firefly Luciferin software just to turn ON/OFF the input boolean.

HA is optional but needed if you want to interact with Luciferin via HA.

hope it helped.

**Comment by Teleportist** [comment]
Thank you. A very clear explanation, which helps a lot.

I may decrease the interval the for gw_time_publisher automation. Just to reduce the traffic.

**Comment by sblantipodi** [comment]
please take into consideration that MQTT server are made to handle very heavy traffic and most MQTT devices polls every 10 seconds by default.

I'm going to close the issue, feel free to open a new one if you have some other questions.
