### ISSUE TITLE
Slowdown & Frame Dropping with MQTT on HT PC.

### ISSUE THREAD

**Issue by Teleportist** [sblantipodi/glow_worm_luciferin#8]
I have Firefly 1.5.0 installed on my Lenovo Thinkcentre M72e Tiny HT PC, running Windows 10 Pro.
https://www.cnet.com/products/lenovo-thinkcentre-m72e-tiny-pentium-g645t-2-5-ghz-2-gb-500-gb-3264t8f
Intel Pentium G645T CPU (dual core, only 2 threads possible), 8GB RAM. SSD drive.

This is communicating via MQTT (mosquito browser add-on within Hassio, running on a Raspberry Pi 3B+)
to a D1 Mini running Glowworm. The PC and RPi are on ethernet. The D1 is obviously wi-Fi.

The issue I have been experiencing is frame dropping and stuttering. Particularly when watching 720p videos
through Kodi. I don't think standard definition is as bad. This is streaming via ethernet from my NAS.

Capture method is set to DDUPL and 1 CPU thread (2 threads unsurprisingly made my machine virtually unresponsive).
The issue happens with FPS set to 30, 20 or 10. Screen resolution is 720x1280.

So 2 questions please;

Is this a problem with Glowworm/Firefly or my hardware?
I was assuming, just sending MQTT commands, with the D1 mini doing all the control wouldn't be any extra load on my PC.

I haven't tried direct connection with USB. Could this eliminate the issue?

Thanks.

**Comment by sblantipodi** [comment]
Hi @Teleportist 
the Intel HD Graphics on your HT PC could be too weak to play a video and to record the screen at the same time.

Set the framerate to 30FPS, 
start the ambient light effect,
right click on the Firefly Luciferin tray icon and click on Info

you should see a windows similar to this:
https://raw.githubusercontent.com/sblantipodi/firefly_luciferin/master/data/img/framerate_counter_javafx_menu.png

please tell me the Producing/Consuming framerate.

**Comment by Teleportist** [comment]
Thanks for the quick reply.

Both the producing and consuming framerates are 30.0

Does the software need to record the whole screen, or is there a way to lower the load by recording
a say just a 50 pixel border from the edge of the screen?

Also, I was looking at upgrading my CPU to an i5-3470T. Which is capable of hyperthreading.

**Comment by sblantipodi** [comment]
the fact that is producing/consuming at 30FPS tell me that it isn't a performance problem.

are you sure that the D1 Mini have a good wifi signal?
can you try with USB Cable?

You should connect the usb cable and uncheck the MQTT Stream checkbox in the Firefly Lucifering config.

**Comment by sblantipodi** [comment]
@Teleportist 
the fact that is producing/consuming at 30FPS tell me that it isn't a performance problem.

are you sure that the D1 Mini have a good wifi signal?
can you try with USB Cable?

You should connect the usb cable and uncheck the MQTT Stream checkbox in the Firefly Lucifering config.

**Comment by Teleportist** [comment]
It was the CPU. I've now upgraded to an i5 and all is well.

Thank you again and sorry for wasting your time.

**Comment by sblantipodi** [comment]
thank you for letting me know it 👍
