### ISSUE TITLE
more leds

### ISSUE THREAD

**Issue by shineofrider** [sblantipodi/glow_worm_luciferin#9]
Hello, great job, very wonderful!
Can I use more than 95 leds? I try to flash last binary and configure 120 leds but only first 95 leds work.
I tried to compile source with 120 leds on file "GlowWormLuciferin.h", the software recognizes my D1 mini but is not work.
Can you help me?
Thank you so mutch!

**Comment by sblantipodi** [comment]
Hi @shineofrider 
thanks for the kind message.

Are you using the light or the full firmware?
Glow Worm Luciferin firmware can handle 120 LEDs without problems but you need to use it's companion PC software Firefly Luciferin.

Are you using [Firefly Luciferin](https://github.com/sblantipodi/firefly_luciferin) ?
If yes, are you sure that you have configured it correctly? 
You can specify the number of LEDs in the firefly luciferin settings.

![settings_screen](https://github.com/sblantipodi/firefly_luciferin/blob/master/data/img/settings_screen.png)

**Comment by shineofrider** [comment]
Sorry, I understand the problem! If I restart the D1 after the software change it works! My mistake was not rebooting the D1 after software changes.
